name = "analytics-with-2"
main = "src/index.ts"
compatibility_date = "2024-07-03"

[[d1_databases]]
binding = "DB"
database_name = "web_analytics_2"
database_id = "<unique-ID-for-your-database>"
